spring.application.name=transfer-service
server.port=${TRANSFER_SERVICE_PORT}

spring.r2dbc.url=${DATABASE_URL}
spring.r2dbc.username=${DATABASE_USER}
spring.r2dbc.password=

spring.rabbitmq.addresses=${RABBITMQ_URL}
transfer.mq.queue=${TRANSFER_INTERBANK_MQ_QUEUE}